### ISSUE TITLE
securepubads.g.doubleclick.net

### ISSUE THREAD

**Issue by jawz101** [dead-hosts/hosts_web_mvps.org#1]
@funilrys 
I'm starting to see several DNS records on my list suddenly inactive.  The most popular I see is 

securepubads.g.doubleclick.net marked INACTIVE.  Is something really happening recently?  Being Google and one of those popular records anyone has seen, it seems weird that it would be INACTIVE.

Attached my most recently list of INACTIVE dns records.  If you scan these do these all look down to you as well?  Thanks
[hosts.txt](https://github.com/dead-hosts/hosts_web_mvps.org/files/3971002/hosts.txt)

**Comment by funilrys** [comment]
Hi @jawz101 sorry for the delay and thanks for the feedback.

As of today, it's distributed as `ACTIVE` https://github.com/dead-hosts/hosts_web_mvps.org/blob/ac8e22ced88a1673fa10b92117f71b1beb7340ae/clean.list#L8150

I did not change the code for the last 15-18 days. So I suppose it's probably because of the [SPECIAL rule](https://pyfunceble.readthedocs.io/en/dev/columns/source.html?highlight=doubleclick#doubleclick-net).

I'll delete the `doubleclick` rule for the good sake of the world. For the follow-up ==> https://github.com/funilrys/PyFunceble/issues/71

Sorry for the inconvenience and thanks again for the feedback.

Cheers!

**Comment by jawz101** [comment]
Thanks.  It just threw me off
